name: root
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.3
  - pip
  - tini
  - fastparquet
  - python-blosc
  - cytoolz
  - dask=2.17.2
  - distributed=2.17.0
  - nomkl
  - numpy=1.18.4
  - pandas=1.0.3
  - lz4
  - s3fs=0.4.2
  - gcsfs
  - scikit-learn=0.23.1
  - scipy
  - xarray
  - zict
  - dask-ml=1.5.0
  - bokeh=2.0