version: "3.7"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack
    hostname: localstack
    networks:
      - localstack-net
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3,sqs,lambda,cloudformation,sts,iam,cloudwatch,apigateway,events
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_REMOVE_CONTAINERS=true
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - ./data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d

  scheduler:
    build:
      context: ./dask
      dockerfile: Dockerfile
    image: daskdev/dask
    hostname: dask-scheduler
    networks:
      - localstack-net
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - localstack

  dask-worker:
    build:
      context: ./dask
      dockerfile: Dockerfile
    image: daskdev/dask
    hostname: dask-worker
    networks:
      - localstack-net
    command: ["dask-worker", "tcp://scheduler:8786"]
    restart: on-failure
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - localstack
      - scheduler

  base-notebook:
    build:
      context: github.com/jupyter/docker-stacks.git#master:base-notebook
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.8.3"
    image: jupyter/base-notebook:lab

  notebook-dask:
    build:
      context: ./dask_s3
      dockerfile: Dockerfile
    container_name: notebook-dask
    image: daskdev/dask-notebook
    depends_on:
      - base-notebook
    hostname: notebook
    networks:
      - localstack-net
    ports:
      - "8888:8888"
    environment:
      - DASK_SCHEDULER_ADDRESS="tcp://scheduler:8786"
    working_dir: /home/jovyan/work
    volumes:
      - ./dask_s3:/home/jovyan/work
      - ./dask_s3/jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py

  redis:
    image: redis:alpine
    hostname: redis
    networks:
      - localstack-net
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

networks:
  localstack-net:
    external: false
    driver: bridge
    name: localstack-net

volumes:
  redis-data: